# UI strings (multilingual)
UI_STRINGS = {
    "English": {
        "title": "🐄 PashuDhan AI",
        "nav_title": "Navigation",
        "tab_predict": "Predict Breed & Chat",
        "tab_ask": "Ask PashuDhanAI (General)",
        "icon_predict": "camera-fill",
        "icon_ask": "chat-dots-fill",
        "enable_audio": "Enable Audio",
        "enable_translation": "Enable Translation",
        "upload": "Upload Image",
        "url": "Image URL",
        "webcam": "Camera",
        "generate": "Generate Response",
        "predicted": "Predicted Breed",
        "confidence": "Confidence",
        "no_model": "Model not found. Place pashu_model.h5 in folder.",
        "no_dataset": "dataset.csv missing.",
        "ask_question": "Ask a Question about the Cattle",
        "select_input": "Select input type",
        "take_photo": "Take photo",
        "choose_image": "Choose image",
        "enter_url": "Enter image URL",
        "response": "Response",
        "invalid_url": "Invalid URL",
        "no_dataset_info": "No dataset info found for this breed.",
        "enter_question": "Enter question.",
        "breed_information": "Breed Information",
        "tts_failed": "Audio failed:",
        "chat_history": "Chat with AI about this Breed",
        "follow_up_placeholder": "Ask a follow-up question about this animal...",
        "separate_section": "Independent Query Section",
        "manual_chat_placeholder": "Ask anything about this breed..."
    },
    "Hindi": {
        "title": "पशुधन AI",
        "nav_title": "नेविगेशन",
        "tab_predict": "नस्ल पहचान और चैट",
        "tab_ask": "पशुधन AI से पूछें (सामान्य)",
        "icon_predict": "camera-fill",
        "icon_ask": "chat-dots-fill",
        "enable_audio": "ऑडियो सक्षम करें",
        "enable_translation": "अनुवाद सक्षम करें",
        "upload": "छवि अपलोड करें",
        "url": "छवि URL",
        "webcam": "वेबकैम का उपयोग करें",
        "generate": "जवाब प्राप्त करें",
        "predicted": "अनुमानित नस्ल",
        "confidence": "विश्वास स्तर",
        "no_model": "मॉडल नहीं मिला। कृपया pashu_model.h5 फ़ोल्डर में रखें।",
        "no_dataset": "dataset.csv नहीं मिला।",
        "ask_question": "पशु के बारे में प्रश्न पूछें",
        "select_input": "इनपुट प्रकार चुनें",
        "take_photo": "फोटो लें",
        "choose_image": "छवि चुनें",
        "enter_url": "छवि URL दर्ज करें",
        "response": "जवाब",
        "invalid_url": "अमान्य URL",
        "no_dataset_info": "इस नस्ल के लिए dataset जानकारी नहीं मिली।",
        "enter_question": "कृपया प्रश्न दर्ज करें।",
        "breed_information": "नस्ल जानकारी",
        "tts_failed": "ऑडियो त्रुटि:",
        "chat_history": "इस नस्ल के बारे में AI से चैट करें",
        "follow_up_placeholder": "इस जानवर के बारे में और सवाल पूछें...",
        "separate_section": "स्वतंत्र प्रश्न अनुभाग",
        "manual_chat_placeholder": "इस नस्ल के बारे में कुछ भी पूछें..."
    },
    "Marathi": {
        "title": "पशुधन AI",
        "nav_title": "नेव्हिगेशन",
        "tab_predict": "जात ओळख आणि चैट",
        "tab_ask": "पशुधन AI ला विचारा (सामान्य)",
        "icon_predict": "camera-fill",
        "icon_ask": "chat-dots-fill",
        "enable_audio": "ऑडिओ सक्षम करा",
        "enable_translation": "भाषांतर सक्षम करा",
        "upload": "प्रतिमा अपलोड करा",
        "url": "प्रतिमा URL",
        "webcam": "वेबकॅम वापरा",
        "generate": "उत्तर तयार करा",
        "predicted": "भाकीत केलेली जात",
        "confidence": "विश्वास",
        "no_model": "मॉडेल सापडले नाही. कृपया pashu_model.h5 ठेवा.",
        "no_dataset": "dataset.csv सापडला नाही.",
        "ask_question": "गुरांबद्दल प्रश्न विचारा",
        "select_input": "इनपुट प्रकार निवडा",
        "take_photo": "फोटो घ्या",
        "choose_image": "प्रतिमा निवडा",
        "enter_url": "प्रतिमा URL भरा",
        "response": "उत्तर",
        "invalid_url": "अवैध URL",
        "no_dataset_info": "या जातीबद्दल dataset माहिती सापडली नाही.",
        "enter_question": "कृपया प्रश्न भरा.",
        "breed_information": "जात माहिती",
        "tts_failed": "ऑडिओ त्रुटी:",
        "chat_history": "AI सोबत चर्चा करा",
        "follow_up_placeholder": "पुढील प्रश्न विचारा...",
        "separate_section": "स्वतंत्र प्रश्न विभाग",
        "manual_chat_placeholder": "या जातीबद्दल काहीही विचारा..."
    },
    "Punjabi": {
        "title": "ਪਸ਼ੁਧਨ AI",
        "nav_title": "ਨੇਵੀਗੇਸ਼ਨ",
        "tab_predict": "ਨਸਲ ਪਹਚਾਣ ਅਤੇ ਚੈਟ",
        "tab_ask": "ਪਸ਼ੂਧਨ AI ਤੋਂ ਪੁੱਛੋ (ਆਮ)",
        "icon_predict": "camera-fill",
        "icon_ask": "chat-dots-fill",
        "enable_audio": "ਆਡੀਓ ਸਮਰੱਥ ਕਰੋ",
        "enable_translation": "ਅਨੁਵਾਦ ਸਮਰੱਥ ਕਰੋ",
        "upload": "ਤਸਵੀਰ ਅਪਲੋਡ ਕਰੋ",
        "url": "ਤਸਵੀਰ URL",
        "webcam": "ਵੇਬਕੈਮ ਨਾਲ ਤਸਵੀਰ ਲਓ",
        "generate": "ਜਵਾਬ ਤਿਆਰ ਕਰੋ",
        "predicted": "ਅਨੁਮਾਨਿਤ ਨਸਲ",
        "confidence": "ਭਰੋਸਾ",
        "no_model": "ਮਾਡਲ ਨਹੀਂ ਮਿਲਿਆ। ਕਿਰਪਾ ਕਰਕੇ pashu_model.h5 ਫੋਲਡਰ ਵਿਚ ਰੱਖੋ।",
        "no_dataset": "dataset.csv ਨਹੀਂ ਮਿਲਿਆ।",
        "ask_question": "ਪਸ਼ੂ ਬਾਰੇ ਪ੍ਰਸ਼ਨ ਪੁੱਛੋ",
        "select_input": "ਇਨਪੁਟ ਕਿਸਮ ਚੁਣੋ",
        "take_photo": "ਫੋਟੋ ਖਿੱਚੋ",
        "choose_image": "ਤਸਵੀਰ ਚੁਣੋ",
        "enter_url": "ਤਸਵੀਰ ਦਾ URL ਦਾਖ਼ਲ ਕਰੋ",
        "response": "ਜਵਾਬ",
        "invalid_url": "ਅਵੈਧ URL",
        "no_dataset_info": "ਇਸ ਨਸਲ ਲਈ ਡੇਟਾਸੇਟ ਜਾਣਕਾਰੀ ਨਹੀਂ ਮਿਲੀ।",
        "enter_question": "ਕਿਰਪਾ ਕਰਕੇ ਪ੍ਰਸ਼ਨ ਦਿਓ।",
        "breed_information": "ਨਸਲ ਜਾਣਕਾਰੀ",
        "tts_failed": "ਆਡੀਓ ਤਰੁੱਟੀ:",
        "chat_history": "AI ਨਾਲ ਗੱਲਬਾਤ ਕਰੋ",
        "follow_up_placeholder": "ਹੋਰ ਸਵਾਲ ਪੁੱਛੋ...",
        "separate_section": "ਵੱਖਰਾ ਸਵਾਲ ਸੈਕਸ਼ਨ",
        "manual_chat_placeholder": "ਇਸ ਨਸਲ ਬਾਰੇ ਕੁਝ ਵੀ ਪੁੱਛੋ..."
    },
}
